version: '2'

services:
  redis:
    image: redis:3.0
    hostname: redis

  rabbitmq:
    image: rabbitmq:3.6.6-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  discovery:
    image: abixen-platform/abixen-platform-eureka
    ports:
      - "8761:8761"

  configuration:
    image: abixen-platform/abixen-platform-configuration
    depends_on:
      - discovery

  gateway:
    image: abixen-platform/abixen-platform-gateway
    depends_on:
      - discovery
      - configuration
      - redis
      - core
      - business-intelligence-service
      - web-content-service
      - zipkin

  business-intelligence-service:
    image: abixen-platform/abixen-platform-business-intelligence-service
    depends_on:
      - discovery
      - configuration
      - business-intelligence-service-postgres-database
      - rabbitmq
      - zipkin

  web-content-service:
    image: abixen-platform/abixen-platform-web-content-service
    depends_on:
      - discovery
      - configuration
      - web-content-service-postgres-database
      - rabbitmq
      - zipkin

  core:
    image: abixen-platform/abixen-platform-core
    depends_on:
      - discovery
      - configuration
      - redis
      - core-postgres-database
      - rabbitmq
      - zipkin
    volumes:
      - ../data/image-library:/data/image-library

  web-client:
    image: abixen-platform/abixen-platform-web-client
    depends_on:
     - discovery
     - configuration
     - gateway
     - core
     - zipkin
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:platform.abixen.devd.io"
      - "traefik.backend.loadbalancer.sticky=true"

  hystrix-dashboard:
    image: abixen-platform/abixen-platform-hystrix-dashboard
    ports:
      - "8989:8989"
    depends_on:
     - gateway
     - core
     - business-intelligence-service
     - web-content-service

  zipkin:
    image: abixen-platform/abixen-platform-zipkin
    ports:
      - "9411:9411"
    depends_on:
     - rabbitmq
     - configuration

  zipkin-web:
    image: abixen-platform/zipkin-web
    build: ../zipkin-web
    ports:
      - "9412:9412"
    depends_on:
     - zipkin

  load-balancer:
    image: traefik:v1.1.2-alpine
    command: --web --docker --docker.domain=devd.io --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    depends_on:
      - web-client

  core-postgres-database:
    image: postgres:9.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: fy2Lkxw201sV
      POSTGRES_USER: abixen
      POSTGRES_DB: abixen_platform_core
    volumes:
      - ../data/db/core:/var/lib/postgresql/data

  business-intelligence-service-postgres-database:
    image: postgres:9.4
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: fy2Lkxw201sV
      POSTGRES_USER: abixen
      POSTGRES_DB: abixen_platform_businessintelligence_service
    volumes:
      - ../data/db/businessintelligence:/var/lib/postgresql/data

  web-content-service-postgres-database:
    image: postgres:9.4
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: fy2Lkxw201sV
      POSTGRES_USER: abixen
      POSTGRES_DB: abixen_platform_web_content_service
    volumes:
      - ../data/db/web_content:/var/lib/postgresql/data

networks:
  default:
