spring:
  application:
    name: abixen-platform-modules

abixen:
  platform:
    modules:
      -
        name: multi-visualization
        title: Multi Visualization
        description: This is a multi visualization module
        relativeInitUrl: /application/modules/abixen/multi-visualization/html/index.html
        staticResources:
          -
            relativeUrl: /application/modules/abixen/modules.min.js
            resourceLocation: BODY
            resourceType: JAVASCRIPT
          -
            relativeUrl: /application/modules/abixen/lib/d3.min.js
            resourceLocation: BODY
            resourceType: JAVASCRIPT
          -
            relativeUrl: /application/modules/abixen/lib/nv.d3.min.js
            resourceLocation: BODY
            resourceType: JAVASCRIPT
          -
            relativeUrl: /application/modules/abixen/lib/nv.d3.min.css
            resourceLocation: HEADER
            resourceType: CSS
          -
            relativeUrl: /application/modules/abixen/lib/angular-nvd3.min.js
            resourceLocation: BODY
            resourceType: JAVASCRIPT
      -
        name: magic-number
        title: Magic Number
        description: This is a magic number module
        relativeInitUrl: /application/modules/abixen/magic-number/html/index.html
        staticResources:
          -
            relativeUrl: /application/modules/abixen/modules.min.js
            resourceLocation: BODY
            resourceType: JAVASCRIPT
      -
        name: kpi-chart
        title: KPI Chart
        description: This is a KPI chart module
        relativeInitUrl: /application/modules/abixen/kpi-chart/html/index.html
        staticResources:
          -
            relativeUrl: /application/modules/abixen/modules.min.js
            resourceLocation: BODY
            resourceType: JAVASCRIPT
          -
            relativeUrl: /application/modules/abixen/lib/roundProgress.min.js
            resourceLocation: BODY
            resourceType: JAVASCRIPT