server:
  port: 9090

security:
  sessions: ALWAYS


---


spring:
  profiles: cloud
  redis:
    host: redis
    port: 6379
  zipkin:
    baseUrl: http://zipkin:9411

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    resource:
      path: /resource/**
      url: http://core:9000
      sensitive-headers:
    api:
      path: /api/**
      url: http://core:9000/api
      sensitive-headers:

    # Begin of custom module microservices - add mapping relevant to your microservice

    # Begin of businessintelligence microservice
    businessintelligenceApplication:
      path: /service/abixen/business-intelligence/application/**
      url: http://business-intelligence-service:9091/service/abixen/business-intelligence/application
      sensitive-headers:
    businessintelligenceAdmin:
      path: /service/abixen/business-intelligence/admin/**
      url: http://business-intelligence-service:9091/service/abixen/business-intelligence/admin
      sensitive-headers:
    # End of businessintelligence microservice

    # Begin of web-content microservice
    webContentApplication:
      path: /service/abixen/web-content/application/**
      url: http://web-content-service:9092/service/abixen/web-content/application
      sensitive-headers:
    webContentAdmin:
      path: /service/abixen/web-content/admin/**
      url: http://web-content-service:9092/service/abixen/web-content/admin
      sensitive-headers:
    # End of web-content microservice

    # End of custom module microservices

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      cluster: AbixenPlatform
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${abixen.services.eureka.uri}:8761/eureka/


---


spring:
  profiles: dev
  redis:
    host: localhost
    port: 6379
  zipkin:
    baseUrl: http://localhost:9411

zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000
      sensitive-headers:
    api:
      path: /api/**
      url: http://localhost:9000/api
      sensitive-headers:
    businessintelligenceApplication:
      path: /service/abixen/business-intelligence/application/**
      url: http://localhost:9091/service/abixen/business-intelligence/application
      sensitive-headers:
    businessintelligenceAdmin:
      path: /service/abixen/business-intelligence/admin/**
      url: http://localhost:9091/service/abixen/business-intelligence/admin
      sensitive-headers:
    webContentApplication:
      path: /service/abixen/web-content/application/**
      url: http://localhost:9092/service/abixen/web-content/application
      sensitive-headers:
    webContentAdmin:
      path: /service/abixen/web-content/admin/**
      url: http://localhost:9092/service/abixen/web-content/admin/
      sensitive-headers:

eureka:
  instance:
    hostname: localhost
    metadataMap:
      cluster: AbixenPlatform
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/