server:
  port: 8080

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    api:
      path: /api/**
      url: http://${abixen.services.gateway.uri:localhost}:9090/api
      sensitive-headers:
    user:
      path: /user
      url: http://${abixen.services.gateway.uri:localhost}:9090/
      sensitive-headers:

    # Begin of custom module microservices - add mapping relevant to your microservice

    # Begin of businessintelligence microservice
    businessintelligenceApplication:
      path: /application/businessintelligence/abixen/**
      serviceId: http://${abixen.services.gateway.uri:localhost}:9090/application/businessintelligence/abixen
      sensitive-headers:
    businessintelligenceAdmin:
      path: /admin/businessintelligence/abixen/**
      url: http://${abixen.services.gateway.uri:localhost}:9090/admin/businessintelligence/abixen
      sensitive-headers:
    # End of businessintelligence microservice

    # Begin of web-content microservice
    webContentApplication:
      path: /application/web-content-service/**
      url: http://${abixen.services.gateway.uri:localhost}:9092/application/web-content-service
      sensitive-headers:
    webContentAdmin:
      path: /admin/web-content-service/**
      url: http://${abixen.services.gateway.uri:localhost}:9092/admin/web-content-service
      sensitive-headers:
    # End of web-content microservice

    # End of custom module microservices

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


---


spring:
  profiles: cloud
  zipkin:
    baseUrl: http://zipkin:9411

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${abixen.services.eureka.uri}:8761/eureka/


---


spring:
  profiles: dev
  zipkin:
    baseUrl: http://localhost:9411

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/