spring:
  application:
    name: abixen-platform-business-intelligence-service

abixen:
  platform:
    adminSidebarItems:
      -
        name: data-source-sidebar-item
        title: Data Sources
        angularJsState: application.multiVisualisation.modules.databaseDataSource.list
        orderIndex: 9
        iconClass: fa fa-database
    modules:
      -
        name: multi-visualisation
        angularJsNameApplication: platformChartModule
        angularJsNameAdmin: TBD
        title: Multi Visualisation
        description: This is a multi visualisation module
        relativeInitUrl: /service/abixen/application/business-intelligence/multi-visualisation/html/index.html
        adminSidebarItems:
          -
            name: data-source-sidebar-item
        staticResources:
          -
            relativeUrl: /service/abixen/application/business-intelligence/business-intelligence.min.css
            resourcePageLocation: HEADER
            resourcePage: APPLICATION
            resourceType: CSS
          -
            relativeUrl: /service/abixen/application/business-intelligence/business-intelligence.min.js
            resourcePageLocation: BODY
            resourcePage: APPLICATION
            resourceType: JAVASCRIPT
          -
            relativeUrl: /service/abixen/application/business-intelligence/lib/d3.min.js
            resourcePageLocation: BODY
            resourcePage: APPLICATION
            resourceType: JAVASCRIPT
          -
            relativeUrl: /service/abixen/application/business-intelligence/lib/nv.d3.min.js
            resourcePageLocation: BODY
            resourcePage: APPLICATION
            resourceType: JAVASCRIPT
          -
            relativeUrl: /service/abixen/application/business-intelligence/lib/nv.d3.min.css
            resourcePageLocation: HEADER
            resourcePage: APPLICATION
            resourceType: CSS
          -
            relativeUrl: /service/abixen/application/business-intelligence/lib/angular-nvd3.min.js
            resourcePageLocation: BODY
            resourcePage: APPLICATION
            resourceType: JAVASCRIPT
          -
            relativeUrl: /service/abixen/admin/business-intelligence/lib/xlsx.full.min.js
            resourcePageLocation: BODY
            resourcePage: ADMIN
            resourceType: JAVASCRIPT
          -
            relativeUrl: /service/abixen/admin/business-intelligence/business-intelligence.min.css
            resourcePageLocation: HEADER
            resourcePage: ADMIN
            resourceType: CSS
          -
            relativeUrl: /service/abixen/admin/business-intelligence/business-intelligence.min.js
            resourcePageLocation: BODY
            resourcePage: ADMIN
            resourceType: JAVASCRIPT
      -
        name: magic-number
        angularJsNameApplication: platformMagicNumberModule
        angularJsNameAdmin: TBD
        title: Magic Number
        description: This is a magic number module
        relativeInitUrl: /service/abixen/application/business-intelligence/magic-number/html/index.html
        staticResources:
          -
            relativeUrl: /service/abixen/application/business-intelligence/business-intelligence.min.css
            resourcePageLocation: HEADER
            resourcePage: APPLICATION
            resourceType: CSS
          -
            relativeUrl: /service/abixen/application/business-intelligence/business-intelligence.min.js
            resourcePageLocation: BODY
            resourcePage: APPLICATION
            resourceType: JAVASCRIPT