spring:
  application:
    name: abixen-platform-business-intelligence-service

abixen:
  platform:
    adminSidebarItems:
      -
        name: data-source-sidebar-item
        title: Data Sources
        angularJsState: application.multiVisualisation.modules.databaseDataSource.list
        orderIndex: 9
        iconClass: fa fa-database
    modules:
      -
        name: multi-visualization
        angularJsNameApplication: platformChartModule
        angularJsNameAdmin: TBD
        title: Multi Visualization
        description: This is a multi visualization module
        relativeInitUrl: /service/abixen/application/businessintelligence/multi-visualization/html/index.html
        adminSidebarItems:
          -
            name: data-source-sidebar-item
        staticResources:
          -
            relativeUrl: /service/abixen/application/businessintelligence/businessintelligence.min.js
            resourcePageLocation: BODY
            resourcePage: APPLICATION
            resourceType: JAVASCRIPT
          -
            relativeUrl: /service/abixen/application/businessintelligence/lib/d3.min.js
            resourcePageLocation: BODY
            resourcePage: APPLICATION
            resourceType: JAVASCRIPT
          -
            relativeUrl: /service/abixen/application/businessintelligence/lib/nv.d3.min.js
            resourcePageLocation: BODY
            resourcePage: APPLICATION
            resourceType: JAVASCRIPT
          -
            relativeUrl: /service/abixen/application/businessintelligence/lib/nv.d3.min.css
            resourcePageLocation: HEADER
            resourcePage: APPLICATION
            resourceType: CSS
          -
            relativeUrl: /service/abixen/application/businessintelligence/lib/angular-nvd3.min.js
            resourcePageLocation: BODY
            resourcePage: APPLICATION
            resourceType: JAVASCRIPT
          -
            relativeUrl: /service/abixen/admin/businessintelligence/lib/xlsx.full.min.js
            resourcePageLocation: BODY
            resourcePage: ADMIN
            resourceType: JAVASCRIPT
      -
        name: magic-number
        angularJsNameApplication: platformMagicNumberModule
        angularJsNameAdmin: TBD
        title: Magic Number
        description: This is a magic number module
        relativeInitUrl: /service/abixen/application/businessintelligence/magic-number/html/index.html
        staticResources:
          -
            relativeUrl: /service/abixen/application/businessintelligence/businessintelligence.min.js
            resourcePageLocation: BODY
            resourcePage: APPLICATION
            resourceType: JAVASCRIPT
      -
        name: kpi-chart
        angularJsNameApplication: platformKpiChartModule
        angularJsNameAdmin: TBD
        title: KPI Chart
        description: This is a KPI chart module
        relativeInitUrl: /service/abixen/application/businessintelligence/kpi-chart/html/index.html
        staticResources:
          -
            relativeUrl: /service/abixen/application/businessintelligence/businessintelligence.min.js
            resourcePageLocation: BODY
            resourcePage: APPLICATION
            resourceType: JAVASCRIPT
          -
            relativeUrl: /service/abixen/application/businessintelligence/lib/roundProgress.min.js
            resourcePageLocation: BODY
            resourcePage: APPLICATION
            resourceType: JAVASCRIPT